apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-final
  labels:
    app: frontend-final
spec:
  replicas: RETORT
  selector:
    matchLabels:
      app: frontend-final
  template:
    metadata:
      labels:
        app: frontend-final
    spec:
      containers:
        - name: frontend-final
          image: DOCKER_IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000