apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodb-volume-mount
              subPath: mongodb
      volumes:
        - name: mongodb-volume-mount
          persistentVolumeClaim:
            claimName: mongodb-pvc