apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-router
  labels:
    app: ingress-router
spec:
  replicas: RETORT
  selector:
    matchLabels:
      app: ingress-router
      tier: backend-final
  template:
    metadata:
      labels:
        app: ingress-router
        tier: backend-final
    spec:
      containers:
        - name: ingress-router
          image: DOCKER_IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP