apiVersion: v1
kind: Service
metadata:
  name: ingress-router
  labels:
    app: ingress-router
spec:
  type: LoadBalancer
  selector:
    app: ingress-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
