apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 100M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disco-gabriela
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: mongodb-pv
