apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-final
  labels:
    app: frontend-final
spec:
  selector:
    matchLabels:
      app: frontend-final
  template:
    metadata:
      labels:
        app: frontend-final
    spec:
      containers:
        - name: frontend-final
          image: DOCKER_IMAGE:TAGç
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API
              valueFrom:
                confingMapKeyRef: 
                  name: frontend-config
                  key: API
